language: go
go: 1.5
sudo: false

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/srclib
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/srclib
  - export PATH=$PATH:$HOME/gopath/bin
  - export GOBIN=$HOME/gopath/bin
  - go get github.com/tools/godep

install:
  - go get -d -v ./...
  - godep restore ./...
  - go build -v ./...
  - go install ./cmd/srclib

script:
  - go test -race -v ./...
  
