language: go

go: 1.5.1

sudo: false

install:

# installing srclib
  - go get -u -v sourcegraph.com/sourcegraph/srclib/cmd/srclib
  - export PATH=$PATH:$HOME/gopath/bin
  - mkdir -p $HOME/.srclib/sourcegraph.com/sourcegraph

# registering C# toolchain
  - ln -s $TRAVIS_BUILD_DIR $HOME/.srclib/sourcegraph.com/sourcegraph/srclib-go
  - srclib toolchain list

  # TODO(keegancsmith) update srclib so that srclib test executes srclib
  - ln -s $HOME/gopath/bin/srclib $HOME/gopath/bin/src
  - chmod +x $HOME/gopath/bin/src*
  - make

# TODO(sqs): add `go test`
script:
  - make srctest
