language: go

go: 1.5.1

sudo: false

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph $HOME/testgopath
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/srclib-go
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/srclib-go
  - cd $TRAVIS_BUILD_DIR
  - export PATH=$PATH:$HOME/gopath/bin
  - export GOBIN=$HOME/gopath/bin

install:
  - go get github.com/tools/godep
  - godep get github.com/sourcegraph/srclib/cmd/srclib
  - srclib toolchain add sourcegraph.com/sourcegraph/srclib-go
  - make

# TODO(sqs): add `go test`
script:
  - make srctest
