language: go

go: 1.5.3

sudo: false

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph $HOME/testgopath
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/srclib-go
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/srclib-go
  - cd $TRAVIS_BUILD_DIR
  - export PATH=$PATH:$HOME/gopath/bin
  - export GOBIN=$HOME/gopath/bin

install:
  - go get -d sourcegraph.com/sourcegraph/srclib/cmd/srclib
  - cd $HOME/gopath/src/sourcegraph.com/sourcegraph/srclib && git checkout 2.0 && cd -
  - go install sourcegraph.com/sourcegraph/srclib/cmd/srclib
  - mkdir -p $HOME/.srclib/sourcegraph.com/sourcegraph
  - ln -s $HOME/gopath/src/sourcegraph.com/sourcegraph/srclib-go $HOME/.srclib/sourcegraph.com/sourcegraph/srclib-go
  - make

# TODO(sqs): add `go test`
script:
  - make srctest
